### ISSUE TITLE
Terminal server problem

### ISSUE THREAD

**Issue by dawkow** [insanerwayner/windowspasswordnotification#2]
Hi when i run script on the Remote desktop server (WS2019) the window with info disappear immediately. No matter if administrator or local user.

**Comment by insanerwayner** [comment]
The script by default won't make the message appear unless it the password expiration is within 7 days. And if the account is set to never expire, it will not run.

Run it with a test user and you can change the parameters to match for testing.

For example: You have a user named **zztest** who's password will expire in 63 days.

```
Check-Password.ps1 -DaysToStart 70 -DaysToMaximizeWindow 3
```

And you can adjust those parameters as needed.

**Comment by insanerwayner** [comment]
Just caught a bug today where there was an extra parenthesis on line 312. Working now in regular windows. Can you update your local copy and test again?

**Comment by dawkow** [comment]
Thx for info i try to test it in next week and give info.

**Comment by insanerwayner** [comment]
> Thx for info i try to test it in next week and give info.

Any luck with testing?

**Comment by insanerwayner** [comment]
No further details supplied
